// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3k1gIssSR6pxYLvtQawlk9ESYdt1RQ7E',
    appId: '1:126634552368:web:3a6c598fb46e1a162a91f5',
    messagingSenderId: '126634552368',
    projectId: 'ai-fitness-c38f0',
    authDomain: 'ai-fitness-c38f0.firebaseapp.com',
    storageBucket: 'ai-fitness-c38f0.firebasestorage.app',
    measurementId: 'G-PEJSHZ2CCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnIXQRxE5f5K7x7LnSjBiT4fCIpWYiD1c',
    appId: '1:126634552368:android:815923c1eaeb7c252a91f5',
    messagingSenderId: '126634552368',
    projectId: 'ai-fitness-c38f0',
    storageBucket: 'ai-fitness-c38f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyTv-wH8_VncVxprsfw-tOKuyeOJ_xpfc',
    appId: '1:126634552368:ios:3dfaf0ce9578790e2a91f5',
    messagingSenderId: '126634552368',
    projectId: 'ai-fitness-c38f0',
    storageBucket: 'ai-fitness-c38f0.firebasestorage.app',
    iosClientId: '126634552368-d5r65aol9mruvhjpstvlmim8p4clbhoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyTv-wH8_VncVxprsfw-tOKuyeOJ_xpfc',
    appId: '1:126634552368:ios:3dfaf0ce9578790e2a91f5',
    messagingSenderId: '126634552368',
    projectId: 'ai-fitness-c38f0',
    storageBucket: 'ai-fitness-c38f0.firebasestorage.app',
    iosClientId: '126634552368-d5r65aol9mruvhjpstvlmim8p4clbhoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3k1gIssSR6pxYLvtQawlk9ESYdt1RQ7E',
    appId: '1:126634552368:web:9a8b7e9f69fc4e1c2a91f5',
    messagingSenderId: '126634552368',
    projectId: 'ai-fitness-c38f0',
    authDomain: 'ai-fitness-c38f0.firebaseapp.com',
    storageBucket: 'ai-fitness-c38f0.firebasestorage.app',
    measurementId: 'G-R5D1L30S72',
  );

}