// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChLgQ1cX__COAhAnSHK5ShPzTYTJVjxXY',
    appId: '1:895851221884:web:45b4df28930a7922cb8af9',
    messagingSenderId: '895851221884',
    projectId: 'tokyo-list-478804-e5',
    authDomain: 'tokyo-list-478804-e5.firebaseapp.com',
    storageBucket: 'tokyo-list-478804-e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Ib3TvO98qOIBmSVT7GVBaqDJpnvpls0',
    appId: '1:895851221884:android:69a794cec56d3b1dcb8af9',
    messagingSenderId: '895851221884',
    projectId: 'tokyo-list-478804-e5',
    storageBucket: 'tokyo-list-478804-e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAasuKG52jZzT2rLh9vaPj_nGqgZ7W-myw',
    appId: '1:895851221884:ios:f30b4eb0204f5ab1cb8af9',
    messagingSenderId: '895851221884',
    projectId: 'tokyo-list-478804-e5',
    storageBucket: 'tokyo-list-478804-e5.firebasestorage.app',
    iosClientId:
        '895851221884-90cbim4om84oc32tl1hsllu2rc8pmra9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAasuKG52jZzT2rLh9vaPj_nGqgZ7W-myw',
    appId: '1:895851221884:ios:f30b4eb0204f5ab1cb8af9',
    messagingSenderId: '895851221884',
    projectId: 'tokyo-list-478804-e5',
    storageBucket: 'tokyo-list-478804-e5.firebasestorage.app',
    iosClientId:
        '895851221884-90cbim4om84oc32tl1hsllu2rc8pmra9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChLgQ1cX__COAhAnSHK5ShPzTYTJVjxXY',
    appId: '1:895851221884:web:07a9f4a94f794b9ecb8af9',
    messagingSenderId: '895851221884',
    projectId: 'tokyo-list-478804-e5',
    authDomain: 'tokyo-list-478804-e5.firebaseapp.com',
    storageBucket: 'tokyo-list-478804-e5.firebasestorage.app',
  );
}
